apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
{{ include "labels.selector" . | indent 8 }}
    spec:
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.externaldns.image.name }}:{{ .Values.externaldns.image.tag }}"
        imagePullPolicy: {{ .Values.externaldns.image.pullPolicy }}
        args:
        - --source=ingress
        {{- range .Values.externaldns.config.domainFilters }}
        - --domain-filter={{ . }}
        {{- end }}
        - --provider=aws
        - --registry=txt
        - --txt-owner-id={{ .Values.externaldns.config.txtOwnerId }}
      serviceAccountName: {{ template "name" . }}