externaldns:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 0.4.5
  namespace: default
  image:
    name: registry.opensource.zalan.do/teapot/external-dns
    tag: v0.4.5
    pullPolicy: IfNotPresent
  config:
    domainFilters:
    - stakater.com
    - stackator.com
    txtOwnerId: stakater